public interface ScannerConstants
{

    int[] TOKEN_STATE = {  0,   0,  -1,  33,  34,  39,  37,  28,  38,  29,  40,  -1,   2,  41,  27,  31,  32,  30,  -1,  -1,  35,  36,  -1,  -1,  -1,  -1,  18,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,   4,  43,   3,  -1,   5,  -1,  -1,   2,  -1,  42,  45,  44,  46,  -1,  58,  -1,  58,  58,  58,  58,  50,  58,  58,  58,  58,  58,  58,  58,  58,  58,  58,  17,  58,  58,   9,  58,  58,  -1,  -1,  -1,   3,  -1,  -1,  -1,  -1,   2,  -1,  14,  58,  58,  58,  58,  58,  58,  58,  58,  58,  58,  56,  58,  58,  58,  58,  58,  19,  58,  58,  58,  25,  58,  58,  26,  58,  58,  -1,  -1,   3,   6,  -1,   3,   3,   3,  -1,  58,  58,  58,  58,  24,  58,  58,  58,  12,  58,  58,  58,  58,  15,  58,  -1,   7,  52,  58,  58,  58,  58,  -1,   3,  -1,  58,  58,  58,  23,  58,  10,  58,  20,  58,  58,  58,  58,  58,  58,  58,  58,  11,  58,  48,   0,  58,  49,  58,  58,  58,   8,  55,  58,  58,  58,  58,  58,  13,  58,  58,  58,  58,  16,  51,  58,  57,   2,  58,  58,  53,  54,  22,  58,   3,  58,  47,  58,  21 };

    String[] SCANNER_ERROR =
    {
        "Caractere não esperado",
        "",
        "Erro identificando CLITERAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_real",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando id",
        "Erro identificando id",
        "",
        "",
        "Erro identificando ate ou id",
        "Erro identificando booleano ou id",
        "Erro identificando const ou cadeia ou caracter ou id",
        "Erro identificando decl ou de ou id",
        "",
        "Erro identificando funcao ou faca ou falso ou fim ou id",
        "Erro identificando intervalo ou inteiro ou inicio ou id",
        "Erro identificando leia ou literal ou id",
        "Erro identificando num_int ou num_real ou nao ou id",
        "Erro identificando ou ou id",
        "Erro identificando proc ou id",
        "Erro identificando repita ou ref ou real ou id",
        "Erro identificando se ou senao ou id",
        "Erro identificando verdadeiro ou val ou vetor ou id",
        "",
        "",
        "",
        "Erro identificando COMMENTBLOCK",
        "",
        "Erro identificando num_real",
        "Erro identificando num_real",
        "",
        "Erro identificando num_int ou num_real",
        "",
        "",
        "",
        "",
        "Erro identificando id",
        "",
        "Erro identificando id",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_real",
        "Erro identificando num_real",
        "Erro identificando COMMENTBLOCK",
        "",
        "Erro identificando num_real",
        "Erro identificando num_real",
        "Erro identificando num_int",
        "Erro identificando num_real",
        "",
        "Erro identificando <ignorar>",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_real",
        "Erro identificando num_real",
        "",
        "",
        "Erro identificando num_real",
        "",
        "",
        "",
        "Erro identificando <ignorar>",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_int ou num_real ou id",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_real",
        "",
        "Erro identificando <ignorar>",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    };

}
