package compilerSemantic;

public interface ScannerConstants
{

    int[] TOKEN_STATE = {  0,   0,  31,  32,  39,  37,  26,  38,  27,  40,   2,   2,  -1,  25,  29,  30,  28,  -1,  24,  33,  34,  24,  24,  24,  11,  24,  24,  24,  24,  24,  24,  24,  24,  24,  35,  36,   3,  -1,  -1,   2,  41,  43,  42,  44,  -1,  -1,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  10,  24,  24,   4,  24,  -1,  -1,   3,  -1,  -1,  -1,   2,   2,  -1,  -1,  24,  24,  24,  17,  24,  24,  24,  24,  24,  24,  24,  24,  12,  24,  24,  24,  24,  24,  -1,  -1,   3,   3,  -1,   3,   3,   3,  -1,  24,  24,  24,  24,  24,  24,   7,  24,  24,   8,  24,  -1,  24,  20,  24,  24,  -1,   3,  -1,  24,  24,  24,  24,   5,  24,  13,  24,  24,  24,  24,  24,   6,  24,   0,  24,  18,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,   9,  19,  23,   2,  24,  24,  24,  21,  22,  15,   3,  16,  24,  24,  14 };

    String[] SCANNER_ERROR =
    {
        "Caractere não esperado",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando <ignorar> ou \":=\"",
        "",
        "",
        "",
        "",
        "Erro identificando id",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_real",
        "Erro identificando num_int ou num_real",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando id",
        "Erro identificando id",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_real",
        "Erro identificando num_real",
        "",
        "Erro identificando num_real",
        "Erro identificando num_int",
        "Erro identificando num_real",
        "",
        "",
        "Erro identificando num_real",
        "Erro identificando <ignorar>",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_real",
        "Erro identificando num_real",
        "",
        "",
        "Erro identificando num_real",
        "",
        "",
        "",
        "Erro identificando <ignorar>",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando num_int ou num_real ou id",
        "",
        "",
        "",
        "",
        "Erro identificando num_real",
        "",
        "Erro identificando <ignorar>",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    };

}
